import { useEffect, useState } from "react";
import { ChevronDown, Clock3, FileSearch, History, Sparkles } from "lucide-react";

type AuditEntry = { agent_name: string; start_time: string; end_time: string | null; execution_time_ms: number | null; status: "running" | "completed" | "failed" | "pending"; summary: string };
type Props = { auditTrail: AuditEntry[]; result: any };
const details: Record<string, { icon: typeof History; color: string }> = { "OCR Agent": { icon: FileSearch, color: "text-blue-600 bg-blue-50" }, "Classification Agent": { icon: Sparkles, color: "text-violet-600 bg-violet-50" }, "Header Agent": { icon: FileSearch, color: "text-indigo-600 bg-indigo-50" }, "Line Item Agent": { icon: FileSearch, color: "text-indigo-600 bg-indigo-50" }, "Vendor Memory Agent": { icon: History, color: "text-emerald-600 bg-emerald-50" }, "Confidence Agent": { icon: Sparkles, color: "text-blue-600 bg-blue-50" }, "Validation Agent": { icon: FileSearch, color: "text-emerald-600 bg-emerald-50" }, "Retry Agent": { icon: History, color: "text-amber-600 bg-amber-50" }, "Header Retry": { icon: History, color: "text-amber-600 bg-amber-50" }, "Line Item Retry": { icon: History, color: "text-amber-600 bg-amber-50" } };
function duration(value: number | null) { if (value === null) return "In progress"; return value < 1000 ? `${value} ms` : `${(value / 1000).toFixed(value >= 10000 ? 1 : 2)} sec`; }

export default function AuditTrailCard({ auditTrail }: Props) { const [expanded, setExpanded] = useState<Set<number>>(new Set()); useEffect(() => { const last = auditTrail.reduce((current, entry, index) => entry.status === "completed" ? index : current, -1); setExpanded(last < 0 ? new Set() : new Set([last])); }, [auditTrail]); if (!auditTrail?.length) return null; return <section className="premium-card rounded-3xl p-5 sm:p-6"><div className="mb-6 flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">Decision ledger</p><h2 className="mt-1 text-xl font-semibold tracking-tight text-slate-900">Audit trail</h2><p className="mt-1 text-sm text-slate-500">Every processing stage is recorded with timing and outcome.</p></div><History className="text-indigo-600" size={22} /></div><div className="space-y-2">{auditTrail.map((entry, index) => { const meta = details[entry.agent_name] ?? { icon: History, color: "text-slate-600 bg-slate-100" }; const Icon = meta.icon; const open = expanded.has(index); const status = entry.status === "completed" ? "bg-emerald-50 text-emerald-700" : entry.status === "failed" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"; return <div key={`${entry.agent_name}-${entry.start_time}`} className={`overflow-hidden rounded-2xl border border-slate-100 ${entry.status === "completed" ? "audit-entry-complete" : ""}`}><button type="button" onClick={() => setExpanded((current) => { const next = new Set(current); next.has(index) ? next.delete(index) : next.add(index); return next; })} aria-expanded={open} className="flex w-full items-center gap-3 p-3 text-left transition hover:bg-slate-50"><span className={`grid h-9 w-9 place-items-center rounded-xl ${meta.color}`}><Icon size={17} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-slate-800">{entry.agent_name}</span><span className="block truncate text-xs text-slate-500">{entry.summary || "Processing stage recorded"}</span></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${status}`}>{entry.status}</span><ChevronDown size={16} className={`text-slate-400 transition ${open ? "rotate-180" : ""}`} /></button>{open && <div className="grid gap-3 border-t border-slate-100 bg-slate-50/70 px-4 py-3 text-sm sm:grid-cols-3"><div><p className="text-xs text-slate-500">Execution time</p><p className="mt-1 flex items-center gap-1 font-semibold text-slate-700"><Clock3 size={13} />{duration(entry.execution_time_ms)}</p></div><div><p className="text-xs text-slate-500">Started</p><p className="mt-1 font-medium text-slate-700">{new Date(entry.start_time).toLocaleString()}</p></div><div><p className="text-xs text-slate-500">Summary</p><p className="mt-1 font-medium text-slate-700">{entry.summary || "No additional details"}</p></div></div>}</div>; })}</div></section>; }
