import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { BarChart3, CheckCircle2, Clock3, RotateCw, TrendingUp, TriangleAlert } from "lucide-react";

import Header from "../components/layout/Header";
import { getAnalytics } from "../services/api";

type Props = { onNavigate: (page: "dashboard" | "analytics" | "history") => void };
function Chart({ title, items, label, tone = "bg-indigo-500" }: { title: string; items: any[]; label: string; tone?: string }) { const maximum = Math.max(...items.map((item) => item.count), 1); return <section className="premium-card rounded-3xl p-5"><h2 className="font-semibold text-slate-900">{title}</h2><div className="mt-5 space-y-4">{items.length === 0 ? <p className="text-sm text-slate-500">No data yet.</p> : items.map((item) => <div key={item[label]}><div className="mb-1.5 flex justify-between gap-3 text-xs"><span className="truncate font-medium text-slate-600">{item[label]}</span><span className="font-bold text-slate-700">{item.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><motion.div initial={{ width: 0 }} animate={{ width: `${item.count / maximum * 100}%` }} className={`h-full rounded-full ${tone}`} /></div></div>)}</div></section>; }
export default function AnalyticsDashboard({ onNavigate }: Props) { const [data, setData] = useState<any>(null); useEffect(() => { getAnalytics().then(setData).catch(console.error); }, []); const stats = [["Total invoices", data?.total_invoices ?? 0, BarChart3, "text-indigo-600 bg-indigo-50"], ["Validation success", `${data?.validation_success_rate ?? 0}%`, CheckCircle2, "text-emerald-600 bg-emerald-50"], ["Auto corrected", data?.invoices_automatically_corrected ?? 0, RotateCw, "text-blue-600 bg-blue-50"], ["Retry success", `${data?.retry_success_rate ?? 0}%`, TrendingUp, "text-emerald-600 bg-emerald-50"], ["Retry failures", `${data?.retry_failure_rate ?? 0}%`, TriangleAlert, "text-amber-600 bg-amber-50"], ["Average retry time", `${data?.average_retry_time_ms ?? 0} ms`, Clock3, "text-violet-600 bg-violet-50"]] as const; return <div className="min-h-screen"><Header activePage="analytics" onNavigate={onNavigate} /><main className="mx-auto max-w-7xl px-4 py-7 sm:px-7"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-indigo-600">Operational intelligence</p><h2 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Analytics dashboard</h2><p className="mt-2 text-sm text-slate-500">Monitor extraction quality, validation health, and autonomous correction outcomes.</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label, value, Icon, tone], index) => <motion.div key={label} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }} className="premium-card rounded-2xl p-5"><div className="flex items-center justify-between"><div className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={19} /></div><span className="text-xs font-medium text-slate-400">Live data</span></div><p className="mt-5 text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">{value}</p></motion.div>)}</section><section className="mt-7 grid gap-5 lg:grid-cols-2"><Chart title="Vendor frequency" items={data?.vendor_frequency ?? []} label="vendor" /><Chart title="Invoice trend" items={data?.invoice_trend ?? []} label="date" tone="bg-blue-500" /><Chart title="Confidence distribution" items={data?.confidence_distribution ?? []} label="range" tone="bg-violet-500" /><Chart title="Validation status" items={data?.validation_status ?? []} label="status" tone="bg-emerald-500" /></section></main></div>; }
